myapp:
  datasource:
    url: jdbc:mysql://60.205.115.71:3306/yupao?serverTimezone=Asia/Shanghai
    username: root
    password: Yl1846869788.
  redis:
    port: 6379
    host: 60.205.115.71
    database: 2
    password: 123123
  server:
    port: 8080


